name: Lint
on: [push, pull_request]

jobs:
  lint:
    strategy:
      fail-fast: false
    runs-on: [ubuntu-22.04, ubuntu-24.04]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: main

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linters
        run: poetry run ./lint.sh
