name: Lint
on: [push, pull_request]

jobs:
  lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Install package
        run: pip install -e .

      - name: Run linters
        run: |
          ./lint.sh
