name: Unit tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run tests
        run: |
          ./test.sh

      - name: Process coverage data
        run: |
          coverage combine
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
